### ISSUE TITLE
Matlab crashes with MEX

### ISSUE THREAD

**Issue by GEMcConnochie** [riccardomarin/FARM-ZOSR#1]
When I run the example MATLAB crashes. I have isolated it to come from calling the mex function d = fastmarchmex('march', march, double(source)); in calc_dist_map.m. 
Do you know what would cause this? 

Thanks
![image](https://user-images.githubusercontent.com/89376037/213359473-1d321692-8277-4584-9dda-b5978ba75c85.png)

**Comment by riccardomarin** [comment]
Hi @GraceEMc ! Thank you for your message.

The problem arises with recent MATLAB versions since the fastmarchmex file is compiled for older ones. Unfortunately, I do not have the source code of it. So the quickest fix is to download an older version of MATLAB (I think that it should work already with 2019a, but you can go further back, like to 2018a). An alternative is to replace that function with anyone else that computes the complete matrix of geodesic distances. A few options are available, but from my experiments, they are much slower than fastmarchmex.

I hope this helps, and let me know if you have further doubts!

**Comment by GEMcConnochie** [comment]
Thanks @riccardomarin. I have tried on MATLAB 2018a but had the same crash occur. Is there a way to recompile the mex file to be compatible?

**Comment by riccardomarin** [comment]
@GraceEMc that's quite strange. 
Could you share your system specifications and a screen of the crash? I will try to replicate the issue and let you know. 

Unfortunately, I do not have the source of the mex to recompile it.

**Comment by GEMcConnochie** [comment]
I figured out I could get the code to run if I inserted a pause or breakpoint before/after running fastmexmerch. So I figure it might have just been overloading my computer or something. Thanks!
